name: ecosyn
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pyqt=6
  - cython
  - pip
  - pip:
    - noise
